Repository ryanisaacg/quicksilver, pull requests merged in 2018-06, with the labels that each got.

#239 Bump deps and add deps.rs badge to readme
  CHANGES.md
  Cargo.toml
  README.md
Labels: version-bump

#241 Add a CONTRIBUTING file to the project
  CONTRIBUTING.md
Labels: documentation-soft

#243 Add an error type specific to saving and loading
  src/error.rs
  src/saving.rs
Labels: enhance-refactor

#244 Fix the description of the font example
  docs/index.html
Labels: documentation-soft

#246 Fix description of the font example
  docs/index.html
Labels: documentation-soft

#248 Add initialization from bytes for Font
  CHANGES.md
  src/graphics/font.rs
Labels: changi-api-compatible, enhance-feature

#250 Fix bug where minimizing the window clears content
  src/input/event.rs
Labels: bug, platform-native, subsystem-graphics

#233 Stdweb integration
  Cargo.toml
  README.md
  src/error.rs
  src/ffi/gl/desktop.rs
  src/ffi/gl/mod.rs
  src/ffi/gl/wasm.rs
  src/ffi/mod.rs
  src/ffi/wasm.rs
  src/file.rs
  src/graphics/backend/gl3.rs
  src/graphics/backend/image_data.rs
  src/graphics/backend/mod.rs
  src/graphics/backend/surface_data.rs
  src/graphics/backend/webgl.rs
  src/graphics/image.rs
  src/graphics/mod.rs
  src/graphics/surface.rs
  src/graphics/window.rs
  src/input/button_state.rs
  src/input/event.rs
  src/input/gamepad.rs
  src/input/mod.rs
  src/input/mouse.rs
  src/lib.rs
  src/saving.rs
  src/sound.rs
  src/state.rs
Labels: change-api-breaking, enhance-feature, platform-wasm, subsystem-graphics, subsystem-input, subsystem-sound, subsystem-util

#253 Remove a possible panic from the Vertex Ord impl
  src/graphics/vertex.rs
Labels: enhance-refactor

#258 Make the font styling a standalone structure
  CHANGES.md
  examples/font.rs
  src/graphics/font.rs
  src/graphics/mod.rs
Labels: change-api-breaking, enhance-feature, subsystem-graphics

#257 Allow the user to customize the letterboxing color
  CHANGES.md
  src/graphics/backend/mod.rs
  src/graphics/vertex.rs
  src/graphics/window.rs
Labels: change-api-breaking, enhance-feature, subsystem-graphics

#260 Bump stdweb
  Cargo.toml
Labels: version-bump

#261 Add Asset to help manage loading futures
  examples/font.rs
  examples/image.rs
  examples/sound.rs
  src/asset.rs
  src/lib.rs
Labels: changi-api-compatible, enhance-feature, enhance-refactor, subsystem-util

#263 Add a line drawing tool
  CHANGES.md
  examples/draw-geometry.rs
  src/graphics/drawable.rs
Labels: changi-api-compatible, enhance-feature, subsystem-graphics

#266 Remove dead functions from lib.rs
  src/lib.rs
Labels: enhance-refactor

#267 Update CONTRIBUTING.md to include git workflow
  CONTRIBUTING.md
Labels: documentation-soft
