Repository ryanisaacg/quicksilver, pull requests merged in 2018-10, with the labels that each got.

#383 Add an example to the tutorial of implementing the Drawable trait
  CHANGES.md
  src/graphics/drawable.rs
  src/tutorials/_11_mesh.rs
Labels: documentation-soft, subsystem-graphics

#385 Add the ability to close the window programmatically
  CHANGES.md
  src/lifecycle/run.rs
  src/lifecycle/window.rs
Labels: change-api-compatible, enhance-feature, platform-native, platform-wasm, subsystem-graphics

#389 Add labels to the example pages
  docs/example.html
Labels: documentation-soft, enhance-infrastructure

#392 Fix MouseWheel Event
  CHANGES.md
  src/lifecycle/event.rs
Labels: bug, platform-native, subsystem-input

#390 Bump version to 0.3.1
  CHANGES.md
  Cargo.toml
  create-release.sh
  docs/camera.example.js
  docs/camera.js
  docs/camera.wasm
  docs/draw-geometry.example.js
  docs/draw-geometry.js
  docs/draw-geometry.wasm
  docs/example.html
  docs/font.example.js
  docs/font.js
  docs/font.wasm
  docs/image.example.js
  docs/image.js
  docs/image.wasm
  docs/lyon.example.js
  docs/lyon.js
  docs/lyon.wasm
  docs/raycast.example.js
  docs/raycast.js
  docs/raycast.wasm
  docs/rgb-triangle.example.js
  docs/rgb-triangle.js
  docs/rgb-triangle.wasm
  docs/sound.example.js
  docs/sound.js
  docs/sound.wasm
  docs/stopwatch.example.js
  docs/stopwatch.js
  docs/stopwatch.wasm
  src/lib.rs
Labels: enhance-version-bump

#391 Add a function to create an Image from a byte Array
  CHANGES.md
  src/graphics/image.rs
  src/tutorials/_05_images.rs
Labels: change-api-compatible, enhance-feature, subsystem-graphics

#342 Add tarpaulin-based codecov support
  .travis.yml
Labels: enhance-infrastructure

#398 Move windows CI builds to Travis
  .travis.yml
  appveyor.yml
Labels: enhance-infrastructure, platform-win32

#400 Fix the derivation of PartialEq on Transform
  CHANGES.md
  src/geom/transform.rs
Labels: bug, subsystem-geometry

#402 Bump version to 0.3.2
  CHANGES.md
  Cargo.toml
  docs/camera.example.js
  docs/camera.wasm
  docs/draw-geometry.example.js
  docs/draw-geometry.wasm
  docs/font.example.js
  docs/font.wasm
  docs/image.example.js
  docs/image.wasm
  docs/lyon.example.js
  docs/lyon.wasm
  docs/raycast.example.js
  docs/raycast.wasm
  docs/rgb-triangle.example.js
  docs/rgb-triangle.wasm
  docs/sound.example.js
  docs/sound.wasm
  docs/stopwatch.example.js
  docs/stopwatch.wasm
  src/lib.rs
Labels: enhance-version-bump
