Repository ryanisaacg/quicksilver, pull requests merged in 2019-03, with the labels that each got.

#471 Fix typed events and some key bindings on web
  CHANGES.md
  src/lifecycle/run.rs
Labels: bug, subsystem-input

#478 Fix for mouse projection issue on web
  CHANGES.md
  src/lifecycle/run.rs
  src/lifecycle/window.rs
Labels: bug, platform-wasm, subsystem-input

#468 Bump dependency versions
  CHANGES.md
  Cargo.toml
  README.md
  examples/lyon.rs
  src/backend/gl3.rs
  src/error.rs
  src/graphics/immi.rs
  src/graphics/lyon.rs
  src/input.rs
  src/input/gamepad.rs
  src/lifecycle.rs
  src/lifecycle/gamepad_provider.rs
  src/lifecycle/window.rs
Labels: enhance-version-bump

#479 Create a prelude module
  CHANGES.md
  src/lib.rs
  src/prelude.rs
Labels: enhance-feature, subsystem-util
